### ISSUE TITLE
 Main document

### ISSUE THREAD

**Issue by milenpi** [AnticraTeam/SRS-QA-Fundamentals#2]
Не ли е добре всичко да се събере в един word документ. Имаме три отделни, и да се вкарат схемите. И общия главен документ да има съдържание. Като гледам в примерните нямат.

**Comment by zlob1l** [comment]
Няма да има после проблем със събирането на файловете - копираме и ги
съединяваме. Просто всичко , което го правя, съм свикнал на нов документ :)
Присъединил съм те към чат във фейса

На 19 април 2016 г., 14:22, milenpi notifications@github.com написа:
